// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/ports_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/fireflg/gophprofile/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAvatarRepository) Create(ctx context.Context, avatar *domain.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAvatarRepositoryMockRecorder) Create(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAvatarRepository)(nil).Create), ctx, avatar)
}

// GetByID mocks base method.
func (m *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByID), ctx, id)
}

// GetLatestByUser mocks base method.
func (m *MockAvatarRepository) GetLatestByUser(ctx context.Context, userID string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUser", ctx, userID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUser indicates an expected call of GetLatestByUser.
func (mr *MockAvatarRepositoryMockRecorder) GetLatestByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUser", reflect.TypeOf((*MockAvatarRepository)(nil).GetLatestByUser), ctx, userID)
}

// ListByUser mocks base method.
func (m *MockAvatarRepository) ListByUser(ctx context.Context, userID string, limit, offset int) ([]*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAvatarRepositoryMockRecorder) ListByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAvatarRepository)(nil).ListByUser), ctx, userID, limit, offset)
}

// Ping mocks base method.
func (m *MockAvatarRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAvatarRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAvatarRepository)(nil).Ping), ctx)
}

// SaveProcessingResult mocks base method.
func (m *MockAvatarRepository) SaveProcessingResult(ctx context.Context, id uuid.UUID, thumbnails map[string]string, width, height int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProcessingResult", ctx, id, thumbnails, width, height)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveProcessingResult indicates an expected call of SaveProcessingResult.
func (mr *MockAvatarRepositoryMockRecorder) SaveProcessingResult(ctx, id, thumbnails, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProcessingResult", reflect.TypeOf((*MockAvatarRepository)(nil).SaveProcessingResult), ctx, id, thumbnails, width, height)
}

// SetProcessingStatus mocks base method.
func (m *MockAvatarRepository) SetProcessingStatus(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProcessingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProcessingStatus indicates an expected call of SetProcessingStatus.
func (mr *MockAvatarRepositoryMockRecorder) SetProcessingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProcessingStatus", reflect.TypeOf((*MockAvatarRepository)(nil).SetProcessingStatus), ctx, id, status)
}

// SetUploadStatus mocks base method.
func (m *MockAvatarRepository) SetUploadStatus(ctx context.Context, id uuid.UUID, status domain.UploadStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUploadStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUploadStatus indicates an expected call of SetUploadStatus.
func (mr *MockAvatarRepositoryMockRecorder) SetUploadStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUploadStatus", reflect.TypeOf((*MockAvatarRepository)(nil).SetUploadStatus), ctx, id, status)
}

// SoftDelete mocks base method.
func (m *MockAvatarRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDelete), ctx, id)
}

// TotalStorageBytes mocks base method.
func (m *MockAvatarRepository) TotalStorageBytes(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalStorageBytes", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalStorageBytes indicates an expected call of TotalStorageBytes.
func (mr *MockAvatarRepositoryMockRecorder) TotalStorageBytes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalStorageBytes", reflect.TypeOf((*MockAvatarRepository)(nil).TotalStorageBytes), ctx)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStorage) Delete(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageMockRecorder) Delete(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorage)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockFileStorage) Get(ctx context.Context, key string) (*domain.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*domain.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFileStorageMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileStorage)(nil).Get), ctx, key)
}

// Ping mocks base method.
func (m *MockFileStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockFileStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockFileStorage)(nil).Ping), ctx)
}

// Put mocks base method.
func (m *MockFileStorage) Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, r, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockFileStorageMockRecorder) Put(ctx, key, r, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockFileStorage)(nil).Put), ctx, key, r, size, contentType)
}

// URL mocks base method.
func (m *MockFileStorage) URL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockFileStorageMockRecorder) URL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockFileStorage)(nil).URL), key)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// Ping mocks base method.
func (m *MockEventPublisher) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEventPublisherMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEventPublisher)(nil).Ping), ctx)
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, event)
}

// MockAvatarUseCase is a mock of AvatarUseCase interface.
type MockAvatarUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUseCaseMockRecorder
	isgomock struct{}
}

// MockAvatarUseCaseMockRecorder is the mock recorder for MockAvatarUseCase.
type MockAvatarUseCaseMockRecorder struct {
	mock *MockAvatarUseCase
}

// NewMockAvatarUseCase creates a new mock instance.
func NewMockAvatarUseCase(ctrl *gomock.Controller) *MockAvatarUseCase {
	mock := &MockAvatarUseCase{ctrl: ctrl}
	mock.recorder = &MockAvatarUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUseCase) EXPECT() *MockAvatarUseCaseMockRecorder {
	return m.recorder
}

// AllowedMimeTypes mocks base method.
func (m *MockAvatarUseCase) AllowedMimeTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowedMimeTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AllowedMimeTypes indicates an expected call of AllowedMimeTypes.
func (mr *MockAvatarUseCaseMockRecorder) AllowedMimeTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowedMimeTypes", reflect.TypeOf((*MockAvatarUseCase)(nil).AllowedMimeTypes))
}

// Delete mocks base method.
func (m *MockAvatarUseCase) Delete(ctx context.Context, id uuid.UUID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarUseCaseMockRecorder) Delete(ctx, id, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarUseCase)(nil).Delete), ctx, id, requesterID)
}

// DeleteUserAvatar mocks base method.
func (m *MockAvatarUseCase) DeleteUserAvatar(ctx context.Context, userID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAvatar", ctx, userID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAvatar indicates an expected call of DeleteUserAvatar.
func (mr *MockAvatarUseCaseMockRecorder) DeleteUserAvatar(ctx, userID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAvatar", reflect.TypeOf((*MockAvatarUseCase)(nil).DeleteUserAvatar), ctx, userID, requesterID)
}

// GetFile mocks base method.
func (m *MockAvatarUseCase) GetFile(ctx context.Context, id uuid.UUID, size, format string) (*domain.FileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, id, size, format)
	ret0, _ := ret[0].(*domain.FileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockAvatarUseCaseMockRecorder) GetFile(ctx, id, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockAvatarUseCase)(nil).GetFile), ctx, id, size, format)
}

// GetMetadata mocks base method.
func (m *MockAvatarUseCase) GetMetadata(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockAvatarUseCaseMockRecorder) GetMetadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockAvatarUseCase)(nil).GetMetadata), ctx, id)
}

// GetUserFile mocks base method.
func (m *MockAvatarUseCase) GetUserFile(ctx context.Context, userID, size, format string) (*domain.FileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFile", ctx, userID, size, format)
	ret0, _ := ret[0].(*domain.FileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFile indicates an expected call of GetUserFile.
func (mr *MockAvatarUseCaseMockRecorder) GetUserFile(ctx, userID, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFile", reflect.TypeOf((*MockAvatarUseCase)(nil).GetUserFile), ctx, userID, size, format)
}

// ListByUser mocks base method.
func (m *MockAvatarUseCase) ListByUser(ctx context.Context, userID string, limit, offset int) ([]*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAvatarUseCaseMockRecorder) ListByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAvatarUseCase)(nil).ListByUser), ctx, userID, limit, offset)
}

// MaxFileSize mocks base method.
func (m *MockAvatarUseCase) MaxFileSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxFileSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// MaxFileSize indicates an expected call of MaxFileSize.
func (mr *MockAvatarUseCaseMockRecorder) MaxFileSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxFileSize", reflect.TypeOf((*MockAvatarUseCase)(nil).MaxFileSize))
}

// URL mocks base method.
func (m *MockAvatarUseCase) URL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockAvatarUseCaseMockRecorder) URL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockAvatarUseCase)(nil).URL), key)
}

// Upload mocks base method.
func (m *MockAvatarUseCase) Upload(ctx context.Context, in domain.UploadInput) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, in)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarUseCaseMockRecorder) Upload(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarUseCase)(nil).Upload), ctx, in)
}
