global:
  scrape_interval: 15s

scrape_configs:
  - job_name: avatars
    static_configs:
      - targets: ["server:9090"]
        labels:
          service: avatars-server
      - targets: ["worker:9090"]
        labels:
          service: avatars-worker

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]
