// Code generated by MockGen. DO NOT EDIT.
// Source: publisher_kafka.go
//
// Generated by this command:
//
//	mockgen -source=publisher_kafka.go -destination=mocks/publisher_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockKafkaWriter is a mock of KafkaWriter interface.
type MockKafkaWriter struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaWriterMockRecorder
	isgomock struct{}
}

// MockKafkaWriterMockRecorder is the mock recorder for MockKafkaWriter.
type MockKafkaWriterMockRecorder struct {
	mock *MockKafkaWriter
}

// NewMockKafkaWriter creates a new mock instance.
func NewMockKafkaWriter(ctrl *gomock.Controller) *MockKafkaWriter {
	mock := &MockKafkaWriter{ctrl: ctrl}
	mock.recorder = &MockKafkaWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaWriter) EXPECT() *MockKafkaWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockKafkaWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockKafkaWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKafkaWriter)(nil).Close))
}

// WriteMessages mocks base method.
func (m *MockKafkaWriter) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockKafkaWriterMockRecorder) WriteMessages(ctx any, msgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockKafkaWriter)(nil).WriteMessages), varargs...)
}

// MockKafkaMetadataClient is a mock of KafkaMetadataClient interface.
type MockKafkaMetadataClient struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaMetadataClientMockRecorder
	isgomock struct{}
}

// MockKafkaMetadataClientMockRecorder is the mock recorder for MockKafkaMetadataClient.
type MockKafkaMetadataClientMockRecorder struct {
	mock *MockKafkaMetadataClient
}

// NewMockKafkaMetadataClient creates a new mock instance.
func NewMockKafkaMetadataClient(ctrl *gomock.Controller) *MockKafkaMetadataClient {
	mock := &MockKafkaMetadataClient{ctrl: ctrl}
	mock.recorder = &MockKafkaMetadataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaMetadataClient) EXPECT() *MockKafkaMetadataClientMockRecorder {
	return m.recorder
}

// Metadata mocks base method.
func (m *MockKafkaMetadataClient) Metadata(ctx context.Context, req *kafka.MetadataRequest) (*kafka.MetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx, req)
	ret0, _ := ret[0].(*kafka.MetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockKafkaMetadataClientMockRecorder) Metadata(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockKafkaMetadataClient)(nil).Metadata), ctx, req)
}
