// Code generated by MockGen. DO NOT EDIT.
// Source: avatar.go
//
// Generated by this command:
//
//	mockgen -source=avatar.go -destination=mocks/usecase_mock.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/fireflg/gophprofile/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarUseCase is a mock of AvatarUseCase interface.
type MockAvatarUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUseCaseMockRecorder
	isgomock struct{}
}

// MockAvatarUseCaseMockRecorder is the mock recorder for MockAvatarUseCase.
type MockAvatarUseCaseMockRecorder struct {
	mock *MockAvatarUseCase
}

// NewMockAvatarUseCase creates a new mock instance.
func NewMockAvatarUseCase(ctrl *gomock.Controller) *MockAvatarUseCase {
	mock := &MockAvatarUseCase{ctrl: ctrl}
	mock.recorder = &MockAvatarUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUseCase) EXPECT() *MockAvatarUseCaseMockRecorder {
	return m.recorder
}

// AllowedMimeTypes mocks base method.
func (m *MockAvatarUseCase) AllowedMimeTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowedMimeTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AllowedMimeTypes indicates an expected call of AllowedMimeTypes.
func (mr *MockAvatarUseCaseMockRecorder) AllowedMimeTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowedMimeTypes", reflect.TypeOf((*MockAvatarUseCase)(nil).AllowedMimeTypes))
}

// Delete mocks base method.
func (m *MockAvatarUseCase) Delete(ctx context.Context, id uuid.UUID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarUseCaseMockRecorder) Delete(ctx, id, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarUseCase)(nil).Delete), ctx, id, requesterID)
}

// DeleteUserAvatar mocks base method.
func (m *MockAvatarUseCase) DeleteUserAvatar(ctx context.Context, userID, requesterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAvatar", ctx, userID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAvatar indicates an expected call of DeleteUserAvatar.
func (mr *MockAvatarUseCaseMockRecorder) DeleteUserAvatar(ctx, userID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAvatar", reflect.TypeOf((*MockAvatarUseCase)(nil).DeleteUserAvatar), ctx, userID, requesterID)
}

// GetFile mocks base method.
func (m *MockAvatarUseCase) GetFile(ctx context.Context, id uuid.UUID, size, format string) (*domain.FileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, id, size, format)
	ret0, _ := ret[0].(*domain.FileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockAvatarUseCaseMockRecorder) GetFile(ctx, id, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockAvatarUseCase)(nil).GetFile), ctx, id, size, format)
}

// GetMetadata mocks base method.
func (m *MockAvatarUseCase) GetMetadata(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockAvatarUseCaseMockRecorder) GetMetadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockAvatarUseCase)(nil).GetMetadata), ctx, id)
}

// GetUserFile mocks base method.
func (m *MockAvatarUseCase) GetUserFile(ctx context.Context, userID, size, format string) (*domain.FileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFile", ctx, userID, size, format)
	ret0, _ := ret[0].(*domain.FileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFile indicates an expected call of GetUserFile.
func (mr *MockAvatarUseCaseMockRecorder) GetUserFile(ctx, userID, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFile", reflect.TypeOf((*MockAvatarUseCase)(nil).GetUserFile), ctx, userID, size, format)
}

// ListByUser mocks base method.
func (m *MockAvatarUseCase) ListByUser(ctx context.Context, userID string, limit, offset int) ([]*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAvatarUseCaseMockRecorder) ListByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAvatarUseCase)(nil).ListByUser), ctx, userID, limit, offset)
}

// MaxFileSize mocks base method.
func (m *MockAvatarUseCase) MaxFileSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxFileSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// MaxFileSize indicates an expected call of MaxFileSize.
func (mr *MockAvatarUseCaseMockRecorder) MaxFileSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxFileSize", reflect.TypeOf((*MockAvatarUseCase)(nil).MaxFileSize))
}

// URL mocks base method.
func (m *MockAvatarUseCase) URL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockAvatarUseCaseMockRecorder) URL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockAvatarUseCase)(nil).URL), key)
}

// Upload mocks base method.
func (m *MockAvatarUseCase) Upload(ctx context.Context, in domain.UploadInput) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, in)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarUseCaseMockRecorder) Upload(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarUseCase)(nil).Upload), ctx, in)
}
