{{- if .Values.networkPolicy.enabled }}
{{- if .Values.networkPolicy.defaultDeny }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "avatars-service.fullname" . }}-default-deny
  labels:
    {{- include "avatars-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "avatars-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "avatars-service.fullname" . }}-allow
  labels:
    {{- include "avatars-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "avatars-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- with .Values.networkPolicy.ingressControllerNamespace }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      ports:
        - port: {{ $.Values.config.http.port }}
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.monitoringNamespace }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      ports:
        - port: {{ $.Values.config.metrics.port }}
          protocol: TCP
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.dns.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.egress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
