apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatars-service.fullname" . }}-worker
  labels:
    {{- include "avatars-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "avatars-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
